const Menu = [
    {
        id: 3,
        image:"images/paratha.png",
        name:"Paratha", 
        category: "Breakfast",
        price: "10",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Immpedit porro sunt illo dolorem dignissimos mollitia fuga qui, unde quam fugiat!",
    },
    {
        id: 4,
        image:"images/Chhola.png",
        name:"Chhola", 
        category: "Lunch",
        price: "50",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit porro sunt illo dolorem dignissimos mollitia fuga qui, unde quam fugiat!",
    },
    {
    id: 1,
    image:"images/maggi.png",
    name:"Maggi", 
    category: "Evening",
    price: "12",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit porro sunt illo dolorem dignissimos mollitia fuga qui, unde quam fugiat!", 
},
{
    id: 2,
    image:"images/aloo-pakoda.png",
    name:"Allu Pakoda", 
    category: "Evening",
    price: "20",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit porro sunt illo dolorem dignissimos mollitia fuga qui, unde quam fugiat!",
},
{
    id: 5,
    image:"images/Pizza.png",
    name:"Pizza", 
    category: "Evening",
    price: "80",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit porro sunt illo dolorem dignissimos mollitia fuga qui, unde quam fugiat!",
},
{
    id: 6,
    image:"images/Non-Veg.png",
    name:"Non-Veg Thali", 
    category: "Dinner",
    price: "180",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit porro sunt illo dolorem dignissimos mollitia fuga qui, unde quam fugiat!",
},
{
    id: 7,
    image:"images/Sweets.png",
    name:"Sweets", 
    category: "Dinner",
    price: "60",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit porro sunt illo dolorem dignissimos mollitia fuga qui, unde quam fugiat!",
},
{
    id: 8,
    image:"images/Rajma.png",
    name:"Rajma Rice", 
    category: "Lunch",
    price: "60",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit porro sunt illo dolorem dignissimos mollitia fuga qui, unde quam fugiat!",
},
{
    id: 9,
    image:"images/Samosa.png",
    name:"Samosa", 
    category: "Evening",
    price: "10",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit porro sunt illo dolorem dignissimos mollitia fuga qui, unde quam fugiat!",
},
{
    id: 10,
    image:"images/Biryani.png",
    name:"Biryani", 
    category: "Dinner",
    price: "50",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit porro sunt illo dolorem dignissimos mollitia fuga qui, unde quam fugiat!",
}]

export default Menu;